language: java
sudo: false

deploy:
  provider: heroku
  api_key:
    secure: LemXJ2/STtlFLUoOUzNWPtqLc72uN7AYN53v1KbDEBj3hQlyOYeXECinYvRnFbgZLpIyaInYf+/g+bJtK24B5Z2SMMYfZ7AMbhYmLMkeHud1eErArNukEbeqOOPtqcX2CMF3d/ggBHorZ8hYpPZjn9MfxXUUzGPld8pMsX6ij9tAFlZW+Ijj7SvHNO9SN0eadkYTevsrtnDk9me1DU6LT9e/zlRiprpXTHLT/SYUdTxSO1kk3luSgNXIt9lbyRqarMEmG1pozupbilgSXQU2OvcT0hrFk2/TFCtLD3L2EVZ5DhRfFD2r0cP4XP+EfiP/mSTwKXk+fAUnwl9DIBFAXrTUFy5CatD3ZD7oN/l4y+9GSKDVBitsYv7UXI1Zm/f8GesjBOE877Ft17X5hxKpI66Oq33R0ERhuhTk6/aly5Nqi96t0Zo8Xt94nPZtApVlr5YLVuGWEL9SyJpUapsoESLhHxigxQE49I1HRW4ahFQ3GBtsinkePN2GNUOcvVT+dmj+fkQkgvf+yGNG7pIUpCi+SIY6X0JoiI6JHo7ZrwhRtcYzVrNNnNcvUc2RoyGXMsLYR6ypIQbnxhtR1idXwgx+lPY6NQk4S0HucoMKtUU1ro9DOtD4Lo+GcgRpVkyIB5rOPfmP+WFfpDlk1HL8j+jNSQ0NLoXltf9uAoD/a/c=
